### ISSUE TITLE
Static files are not served when running from dist

### ISSUE THREAD

**Issue by mmarcon** [thingsinjars/map-playground#4]
$ node dist/server.js

    151104/072958.243, [response], http://0.0.0.0:3000: get /bin/ {} 404 (21ms)
    151104/073009.351, [response], http://0.0.0.0:3000: get /bin/index.html {} 404 (7ms)

**Comment by thingsinjars** [comment]
Is this through nginx? There isn't a /bin/ path in the server so it should 404 there.

**Comment by mmarcon** [comment]
Yes, it's through nginx doing a reverse proxy. That's the same problem I had before you redid the project.

**Comment by thingsinjars** [comment]
My nginx config must be different from yours:

    :
    location /bin/ {
       proxy_pass http://localhost:3000/;
    }
    :

**Comment by mmarcon** [comment]
https://github.com/mmarcon/jhere-devops/blob/playground/ansible/nginx/jhere.playground.conf
